In [3]:
import pandas as pd

In [4]:
file_path = "E:\\LifeExpectancy_DataAnalysis\\primary_dataset.csv"

data = pd.read_csv(file_path)

print(data.head())

   Country          Region  Year  Infant_deaths  Under_five_deaths  \
0  Turkiye     Middle East  2015           11.1               13.0
1    Spain  European Union  2015            2.7                3.3
2    India            Asia  2007           51.5               67.9
3   Guyana   South America  2006           32.8               40.5
4   Israel     Middle East  2012            3.4                4.3

   Adult_mortality  Alcohol_consumption  Hepatitis_B  Measles   BMI  ...  \
0         105.8240                 1.32           97       65  27.8  ...
1          57.9025                10.35           97       94  26.0  ...
2         201.0765                 1.57           60       35  21.2  ...
3         222.1965                 5.68           93       74  25.3  ...
4          57.9510                 2.89           97       89  27.0  ...

   Diphtheria  Incidents_HIV  GDP_per_capita  Population_mln  \
0          97           0.08           11006           78.53
1          97           0.09           25742           46.44
2          64           0.13            1076         1183.21
3          93           0.79            4146            0.75
4          94           0.08           33995            7.91

   Thinness_ten_nineteen_years  Thinness_five_nine_years  Schooling  \
0                          4.9                       4.8        7.8
1                          0.6                       0.5        9.7
2                         27.1                      28.0        5.0
3                          5.7                       5.5        7.9
4                          1.2                       1.1       12.8

   Economy_status_Developed  Economy_status_Developing  Life_expectancy
0                         0                          1             76.5
1                         1                          0             82.8
2                         0                          1             65.4
3                         0                          1             67.0
4                         1                          0             81.7

[5 rows x 21 columns]

In [24]:
#info_data
def info_data(data):
     return(data.info())

info_data(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2864 entries, 0 to 2863
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      2864 non-null   object
 1   Region                       2864 non-null   object
 2   Year                         2864 non-null   int64
 3   Infant_deaths                2864 non-null   float64
 4   Under_five_deaths            2864 non-null   float64
 5   Adult_mortality              2864 non-null   float64
 6   Alcohol_consumption          2864 non-null   float64
 7   Hepatitis_B                  2864 non-null   int64
 8   Measles                      2864 non-null   int64
 9   BMI                          2864 non-null   float64
 10  Polio                        2864 non-null   int64
 11  Diphtheria                   2864 non-null   int64
 12  Incidents_HIV                2864 non-null   float64
 13  GDP_per_capita               2864 non-null   int64
 14  Population_mln               2864 non-null   float64
 15  Thinness_ten_nineteen_years  2864 non-null   float64
 16  Thinness_five_nine_years     2864 non-null   float64
 17  Schooling                    2864 non-null   float64
 18  Economy_status_Developed     2864 non-null   int64
 19  Economy_status_Developing    2864 non-null   int64
 20  Life_expectancy              2864 non-null   float64
dtypes: float64(11), int64(8), object(2)
memory usage: 470.0+ KB

In [21]:
#describe_data
def describe_data(data):
    return data.describe()
    
describe_data(data)

,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
count,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000
mean,2007.500000,30.363792,42.938268,192.251775,4.820882,84.292598,77.344972,25.032926,86.499651,86.271648,0.894288,11540.924930,36.675915,4.865852,4.899825,7.632123,0.206704,0.793296,68.856075
std,4.610577,27.538117,44.569974,114.910281,3.981949,15.995511,18.659693,2.193905,15.080365,15.534225,2.381389,16934.788931,136.485867,4.438234,4.525217,3.171556,0.405012,0.405012,9.405608
min,2000.000000,1.800000,2.300000,49.384000,0.000000,12.000000,10.000000,19.800000,8.000000,16.000000,0.010000,148.000000,0.080000,0.100000,0.100000,1.100000,0.000000,0.000000,39.400000
25%,2003.750000,8.100000,9.675000,106.910250,1.200000,78.000000,64.000000,23.200000,81.000000,81.000000,0.080000,1415.750000,2.097500,1.600000,1.600000,5.100000,0.000000,1.000000,62.700000
50%,2007.500000,19.600000,23.100000,163.841500,4.020000,89.000000,83.000000,25.500000,93.000000,93.000000,0.150000,4217.000000,7.850000,3.300000,3.400000,7.800000,0.000000,1.000000,71.400000
75%,2011.250000,47.350000,66.000000,246.791375,7.777500,96.000000,93.000000,26.400000,97.000000,97.000000,0.460000,12557.000000,23.687500,7.200000,7.300000,10.300000,0.000000,1.000000,75.400000
max,2015.000000,138.100000,224.900000,719.360500,17.870000,99.000000,99.000000,32.100000,99.000000,99.000000,21.680000,112418.000000,1379.860000,27.700000,28.600000,14.100000,1.000000,1.000000,83.800000

In [26]:
#check_normality
from scipy.stats import shapiro

def check_normality(data):
    variables = ['Infant_deaths','Year', 'Under_five_deaths', 'Adult_mortality', 'Alcohol_consumption', 'Hepatitis_B', 
                 'Measles', 'BMI', 'Polio', 'Diphtheria', 'Incidents_HIV', 'GDP_per_capita', 'Population_mln', 
                 'Thinness_ten_nineteen_years', 'Thinness_five_nine_years', 'Schooling', 'Life_expectancy']

    for var in variables:
        stat, p = shapiro(data[var])
        print(f'Variable: {var}')
        print(f'Statistic: {stat}, p-value: {p}')

        if p > 0.05:
            print('Normal distribution: Yes\n')
        else:
            print('Normal distribution: No\n')


check_normality(data)

Variable: Infant_deaths
Statistic: 0.8646653588385218, p-value: 2.289380707152347e-44
Normal distribution: No

Variable: Year
Statistic: 0.9465555306785974, p-value: 4.687800820545888e-31
Normal distribution: No

Variable: Under_five_deaths
Statistic: 0.8157073852291188, p-value: 2.443337410169196e-49
Normal distribution: No

Variable: Adult_mortality
Statistic: 0.8846410706629056, p-value: 6.665827909514486e-42
Normal distribution: No

Variable: Alcohol_consumption
Statistic: 0.9235805094966695, p-value: 6.926800062767792e-36
Normal distribution: No

Variable: Hepatitis_B
Statistic: 0.8141723470446879, p-value: 1.7809443058236373e-49
Normal distribution: No

Variable: Measles
Statistic: 0.8897735972657685, p-value: 3.2560568186539293e-41
Normal distribution: No

Variable: BMI
Statistic: 0.9711858054836555, p-value: 1.4254576893265388e-23
Normal distribution: No

Variable: Polio
Statistic: 0.7815232840465938, p-value: 3.398662682683381e-52
Normal distribution: No

Variable: Diphtheria
Statistic: 0.7705926429881689, p-value: 4.9698554619975045e-53
Normal distribution: No

Variable: Incidents_HIV
Statistic: 0.3820460719482075, p-value: 1.8591494673725038e-71
Normal distribution: No

Variable: GDP_per_capita
Statistic: 0.6705374038497984, p-value: 1.9599001503701852e-59
Normal distribution: No

Variable: Population_mln
Statistic: 0.22687254820705394, p-value: 5.155090398154736e-76
Normal distribution: No

Variable: Thinness_ten_nineteen_years
Statistic: 0.8387364894600229, p-value: 3.722742227350195e-47
Normal distribution: No

Variable: Thinness_five_nine_years
Statistic: 0.8349303653949758, p-value: 1.5598135496070148e-47
Normal distribution: No

Variable: Schooling
Statistic: 0.9680869206163019, p-value: 9.81587248586395e-25
Normal distribution: No

Variable: Life_expectancy
Statistic: 0.9349650108561698, p-value: 1.1611718329512556e-33
Normal distribution: No